import { YouTubeNiche, NicheCategoryConfig, ColorTheme, ThumbnailLayout, LayoutMetadata, FontPreset } from './types';

export const THUMBNAIL_LAYOUTS: LayoutMetadata[] = [
  {
    id: 'split-face-punchy',
    name: 'Split Subject + Massive Text',
    category: 'High CTR',
    description: 'High-contrast split screen with subject cutout on one side and punchy 2-line boxed headline on the other.',
    badge: 'TOP CTR',
    icon: '⚡',
    bestFor: 'Tutorials, Vlogs, Coding, Explanations',
  },
  {
    id: 'centered-shock',
    name: 'Centered Subject & Dual Banners',
    category: 'High Energy',
    description: 'Center focal headshot/subject flanked by electrified top danger banner and bold bottom urgency box.',
    badge: 'VIRAL',
    icon: '🚨',
    bestFor: 'Reactions, Dramatic Stories, Big Announcements',
  },
  {
    id: 'before-after-split',
    name: 'Before vs After Split',
    category: 'Comparison',
    description: 'Red "BEFORE" vs Green "AFTER" comparison split with glowing center "VS" battle badge.',
    badge: 'HIGH CONVERSION',
    icon: '⚖️',
    bestFor: 'Transformations, Redesigns, Case Studies, Fitness',
  },
  {
    id: 'cinematic-dark-luxury',
    name: 'Cinematic Dark Luxury',
    category: 'Documentary',
    description: 'Moody 35mm film vignette with gold embossed typography, verified case study card, and sleek aesthetics.',
    badge: 'PREMIUM',
    icon: '🎬',
    bestFor: 'Documentaries, Finance, Tech Deep Dives, Stories',
  },
  {
    id: 'tech-cyber-neon',
    name: 'Cyberpunk & Tech Matrix',
    category: 'Technology',
    description: 'Holographic cyan/magenta grid, glowing subject rim outline, cyber corner brackets, and code pill tags.',
    badge: 'TECH FAVORITE',
    icon: '🤖',
    bestFor: 'AI Tools, Coding, Software, SaaS, Hardware',
  },
  {
    id: 'gaming-high-energy',
    name: 'Gaming High Energy Slash',
    category: 'Gaming',
    description: 'Dynamic diagonal lightning split, flame glow aura, and bold slanted action typography.',
    badge: 'GAMING',
    icon: '🔥',
    bestFor: 'Let’s Plays, Esports, Challenges, Minecraft',
  },
  {
    id: 'educational-checklist',
    name: 'Numbered Checklist & Pills',
    category: 'Educational',
    description: 'Presenter cutout on left with 3 high-contrast numbered bullet pill cards and custom checkmarks.',
    badge: 'EDUCATIONAL',
    icon: '📝',
    bestFor: 'Step-by-step Guides, Roadmaps, Tips & Tricks',
  },
  {
    id: 'breaking-news-urgent',
    name: 'Breaking News Urgent Alert',
    category: 'Urgency',
    description: 'Crimson alert top bar with yellow hazard caution stripes, urgent headline box, and dramatic framing.',
    badge: 'NEWS ALERT',
    icon: '⚠️',
    bestFor: 'Current Events, Tech Policy, Exposes, Breaking Updates',
  },
  {
    id: 'stat-shock-minimal',
    name: 'Stat Shock & Case Study',
    category: 'Finance',
    description: 'Massive stat metric ($0 ➔ $50K) with sleek subtitle bar and minimalist modern studio layout.',
    badge: 'FINANCE',
    icon: '📈',
    bestFor: 'Income Reports, Growth Metrics, Marketing Case Studies',
  },
  {
    id: 'device-app-mockup',
    name: 'App & Device Mockup',
    category: 'Product',
    description: 'Floating 3D device/software mockup frame with glowing highlight border and feature pills.',
    badge: 'PRODUCT',
    icon: '📱',
    bestFor: 'App Reviews, Tool Demos, Website Showcases',
  },
  {
    id: 'reaction-face-burst',
    name: 'Reaction Cutout & Comic Burst',
    category: 'Entertainment',
    description: 'Expressive creator reaction cutout with comic explosion stamp and bold warning subtitle.',
    badge: 'REACTION',
    icon: '😱',
    bestFor: 'Reaction Videos, Commentary, Pop Culture, Surprises',
  },
  {
    id: 'podcast-interview-duo',
    name: 'Podcast & Guest Interview',
    category: 'Interview',
    description: 'Dual guest/host avatar circles with glowing center audio waveform, microphone badge, and episode header.',
    badge: 'PODCAST',
    icon: '🎙️',
    bestFor: 'Interviews, Talk Shows, Podcasts, Debates',
  },
  {
    id: 'versus-rivalry-battle',
    name: 'Versus Rivalry & Battle',
    category: 'Comparison',
    description: 'Blue Corner vs Red Corner split with epic lightning division line and glowing 3D "VS" battle emblem.',
    badge: 'HEAD-TO-HEAD',
    icon: '⚔️',
    bestFor: 'Product Battles, Brand Comparisons, Gaming 1v1',
  },
  {
    id: 'secret-revealed-blur',
    name: 'The Secret Revealed & Red Arrow',
    category: 'Curiosity Hook',
    description: 'Focal subject with glowing directional red pointer arrow and high-voltage "THE SECRET" mystery badge.',
    badge: 'HIGH CURIOSITY',
    icon: '🔍',
    bestFor: 'Secrets, Hacks, Hidden Features, Mysteries',
  },
  {
    id: 'top-listicle-ranking',
    name: 'Top Ranking & Crown Trophy',
    category: 'Listicle',
    description: 'Gold crown trophy stamp with massive gradient rank number (#1 / TOP 10) and punchy 2-line sub-headline.',
    badge: 'TOP RANKING',
    icon: '👑',
    bestFor: 'Top 5/10 Lists, Best Of 2026, Tier Lists, Rankings',
  },
  {
    id: 'viral-10x-arrow',
    name: '10X Views & 3D Green Arrow',
    category: 'Viral Hook',
    description: 'Surprised face on side + Slanted punchy text + Glowing 3D Green Trending Arrow + "10X MORE VIEWS!" badge.',
    badge: 'VIRAL HOOK',
    icon: '📈',
    bestFor: 'Growth Hacks, Viral Tips, Channel Boost, Case Studies',
  },
  {
    id: 'bold-3d-title-plate',
    name: '3D Stacked Title & Glossy YouTube Button',
    category: 'High CTR',
    description: 'Massive 3D extruded title banners with 3D glossy red YouTube button, shocked face, and radiant energy burst.',
    badge: 'LEGIIT TOP SELLER',
    icon: '▶️',
    bestFor: 'Main Channel Videos, Tutorials, Vlogs, Big Announcements',
  },
  {
    id: 'money-wealth-blueprint',
    name: 'Income Reveal & Cash Stacks ($50K/MO)',
    category: 'Finance',
    description: '"$50,000 PER MONTH" high-voltage cash stats, money stack icons, gold gradient glow, and presenter pointing.',
    badge: 'WEALTH BLUEPRINT',
    icon: '💵',
    bestFor: 'Passive Income, Side Hustles, Crypto, Finance, Dropshipping',
  },
  {
    id: 'doodle-chalk-arrow',
    name: 'Chalk Doodle Loop & Pointer Arrow',
    category: 'Curiosity Hook',
    description: 'Hand-drawn white doodle loops + curved chalk arrow pointing to shocked face with high-contrast badge.',
    badge: 'HIGH CURIOSITY',
    icon: '🎯',
    bestFor: 'Psychology, Mysteries, "The Most Attractive", Secrets',
  },
  {
    id: 'thumbnail-inception-grid',
    name: 'Thumbnail Inception & Showcase Grid',
    category: 'Creative',
    description: 'Floating multi-thumbnail previews grid + creator pointing finger + "HOW TO MAKE THUMBNAILS LIKE THIS" title.',
    badge: 'SHOWCASE',
    icon: '🖼️',
    bestFor: 'Design Tutorials, Portfolio Reviews, Before/After Multi-Packs',
  },
  {
    id: 'laser-eyes-shock',
    name: 'Laser Eyes Surge & Energy Blast',
    category: 'High Energy',
    description: 'Neon glowing laser eye beams + high-voltage energy blast + "10X MORE VIEWS" neon pill badge.',
    badge: 'ENERGY SURGE',
    icon: '👁️',
    bestFor: 'Crypto Hype, Tech Shocks, Insane Challenges, Gaming',
  },
];

export const NICHE_PRESETS: Record<YouTubeNiche, NicheCategoryConfig> = {
  technology: {
    id: 'technology',
    name: 'Technology & Software',
    subcategories: ['Coding & Web Dev', 'Software & Tools', 'Gadgets & Reviews', 'Cybersecurity', 'SaaS', 'Future Tech'],
    defaultStyle: 'tech-cyber-neon',
    suggestedPalettes: ['cyber-cyan', 'electric-neon', 'monochrome-bold'],
    sampleTitles: [
      'How I Built a Full Stack App in 30 Minutes',
      'The Death of Traditional Web Development in 2026',
      'Why Senior Engineers Are Leaving Big Tech',
    ],
  },
  education: {
    id: 'education',
    name: 'Education & Tutorials',
    subcategories: ['How-To Guides', 'Science & Physics', 'Languages', 'Coding Crash Courses', 'Productivity & Study', 'Math & Logic'],
    defaultStyle: 'educational-checklist',
    suggestedPalettes: ['electric-neon', 'emerald-wealth', 'youtube-classic'],
    sampleTitles: [
      'The Only Python Roadmap You Need in 2026',
      'Learn Calculus in 45 Minutes (Visual Proofs)',
      '3 Study Habits That Got Me Into Harvard',
    ],
  },
  business: {
    id: 'business',
    name: 'Business & Finance',
    subcategories: ['Stock Market & Investing', 'Real Estate', 'Crypto & Bitcoin', 'E-Commerce & Shopify', 'Freelancing & Agency', 'Startups & Venture Capital'],
    defaultStyle: 'stat-shock-minimal',
    suggestedPalettes: ['emerald-wealth', 'luxury-gold', 'electric-neon'],
    sampleTitles: [
      'How I Make $10,000/Month on Fiverr as a Beginner',
      '5 Index Funds to Buy and Hold Forever',
      'The 4-Hour Work Week: Real-World Blueprint',
    ],
  },
  entertainment: {
    id: 'entertainment',
    name: 'Entertainment & Gaming',
    subcategories: ['Gaming & Esports', 'Movies & Pop Culture', 'Reaction Videos', 'Vlogs & Storytelling', 'Travel & Adventure', 'Fitness & Challenges'],
    defaultStyle: 'gaming-high-energy',
    suggestedPalettes: ['sunset-orange', 'youtube-classic', 'vibrant-purple'],
    sampleTitles: [
      'I Survived 100 Days in Hardcore Minecraft',
      'Movie Director Reacts to Worst CGI in Hollywood History',
      'We Traveled to the Most Dangerous Island in the World',
    ],
  },
  news: {
    id: 'news',
    name: 'News & Information',
    subcategories: ['News Analysis', 'Deep Explainers', 'Current Events', 'Historical Documentaries', 'True Crime', 'Tech Policy & Geopolitics'],
    defaultStyle: 'breaking-news-urgent',
    suggestedPalettes: ['crimson-alert', 'monochrome-bold', 'luxury-gold'],
    sampleTitles: [
      'The Shocking Collapse of the Tech Industry Explained',
      'What Really Happened: The Untold Investigation',
      'The Global Crisis Nobody Is Talking About',
    ],
  },
  creative: {
    id: 'creative',
    name: 'Creative & Design',
    subcategories: ['UI/UX Design', 'Photography', 'Video Editing & Premiere', '3D & Blender', 'Content Creation', 'Music Production'],
    defaultStyle: 'cinematic-dark-luxury',
    suggestedPalettes: ['vibrant-purple', 'luxury-gold', 'sunset-orange'],
    sampleTitles: [
      'Top 10 Figma Secrets Senior Designers Never Share',
      'Edit Videos 10x Faster: Pro Premiere Pro Workflow',
      'The Secret Color Grading Formula of Hollywood Movies',
    ],
  },
  custom: {
    id: 'custom',
    name: 'Custom / General',
    subcategories: ['General', 'Podcast', 'Documentary', 'Lifestyle', 'Coaching', 'Review'],
    defaultStyle: 'split-face-punchy',
    suggestedPalettes: ['electric-neon', 'youtube-classic', 'emerald-wealth'],
    sampleTitles: [
      'Stop Making This Mistake Before It Is Too Late',
      'The Ultimate Guide to Starting in 2026',
      'Everything You Were Told Was Wrong',
    ],
  },
};

export const COLOR_THEMES: ColorTheme[] = [
  // 1. High CTR Viral & Punchy
  {
    id: 'electric-neon',
    name: 'Electric Neon & Charcoal (Top CTR)',
    category: 'High CTR',
    bgGradient: ['#0f172a', '#020617'],
    primaryAccent: '#f59e0b',
    highlightColor: '#facc15',
    textColor: '#ffffff',
    textMuted: '#94a3b8',
    badgeBg: '#facc15',
    badgeText: '#000000',
    cardBg: 'rgba(15, 23, 42, 0.85)',
    cardBorder: 'rgba(250, 204, 21, 0.35)',
    glowColor: '#facc15',
  },
  {
    id: 'youtube-classic',
    name: 'YouTube Classic (Red & Black)',
    category: 'High CTR',
    bgGradient: ['#18181b', '#050507'],
    primaryAccent: '#ef4444',
    highlightColor: '#ff2222',
    textColor: '#ffffff',
    textMuted: '#a1a1aa',
    badgeBg: '#ff0000',
    badgeText: '#ffffff',
    cardBg: 'rgba(24, 24, 27, 0.9)',
    cardBorder: 'rgba(239, 68, 68, 0.4)',
    glowColor: '#ef4444',
  },
  {
    id: 'radioactive-lime',
    name: 'Radioactive Lime & Deep Space (Viral High CTR)',
    category: 'High CTR',
    bgGradient: ['#051a0e', '#010804'],
    primaryAccent: '#10b981',
    highlightColor: '#00ff66',
    textColor: '#ffffff',
    textMuted: '#6ee7b7',
    badgeBg: '#00ff66',
    badgeText: '#000000',
    cardBg: 'rgba(5, 26, 14, 0.9)',
    cardBorder: 'rgba(0, 255, 102, 0.45)',
    glowColor: '#00ff66',
  },
  {
    id: 'hyper-orange',
    name: 'Hyper Solar Orange & Navy (High Energy)',
    category: 'High CTR',
    bgGradient: ['#1e1308', '#070502'],
    primaryAccent: '#ea580c',
    highlightColor: '#ff6b00',
    textColor: '#ffffff',
    textMuted: '#fdba74',
    badgeBg: '#ff6b00',
    badgeText: '#000000',
    cardBg: 'rgba(30, 19, 8, 0.9)',
    cardBorder: 'rgba(255, 107, 0, 0.45)',
    glowColor: '#ff6b00',
  },

  // 2. Gaming, Cyber & Esports
  {
    id: 'cyber-cyan',
    name: 'Cyber Cyan & Deep Navy (Tech Matrix)',
    category: 'Gaming & Cyber',
    bgGradient: ['#031626', '#01080f'],
    primaryAccent: '#06b6d4',
    highlightColor: '#00f0ff',
    textColor: '#ffffff',
    textMuted: '#94a3b8',
    badgeBg: '#00f0ff',
    badgeText: '#000000',
    cardBg: 'rgba(6, 182, 212, 0.12)',
    cardBorder: 'rgba(0, 240, 255, 0.45)',
    glowColor: '#00f0ff',
  },
  {
    id: 'vibrant-purple',
    name: 'Electric Purple & Ultraviolet (Gaming)',
    category: 'Gaming & Cyber',
    bgGradient: ['#230648', '#090114'],
    primaryAccent: '#a855f7',
    highlightColor: '#d946ef',
    textColor: '#ffffff',
    textMuted: '#e9d5ff',
    badgeBg: '#d946ef',
    badgeText: '#ffffff',
    cardBg: 'rgba(35, 6, 72, 0.85)',
    cardBorder: 'rgba(217, 70, 239, 0.45)',
    glowColor: '#d946ef',
  },
  {
    id: 'synthwave-80s',
    name: 'Synthwave Neon Pink & Indigo (Retro Wave)',
    category: 'Gaming & Cyber',
    bgGradient: ['#280436', '#0a0110'],
    primaryAccent: '#06b6d4',
    highlightColor: '#ff1493',
    textColor: '#ffffff',
    textMuted: '#f472b6',
    badgeBg: '#ff1493',
    badgeText: '#ffffff',
    cardBg: 'rgba(40, 4, 54, 0.9)',
    cardBorder: 'rgba(255, 20, 147, 0.45)',
    glowColor: '#ff1493',
  },
  {
    id: 'esports-crimson',
    name: 'Esports Crimson & Carbon (Action Slant)',
    category: 'Gaming & Cyber',
    bgGradient: ['#200408', '#070002'],
    primaryAccent: '#f43f5e',
    highlightColor: '#ff003c',
    textColor: '#ffffff',
    textMuted: '#fda4af',
    badgeBg: '#ff003c',
    badgeText: '#ffffff',
    cardBg: 'rgba(32, 4, 8, 0.9)',
    cardBorder: 'rgba(255, 0, 60, 0.5)',
    glowColor: '#ff003c',
  },

  // 3. Finance, Wealth & Luxury
  {
    id: 'emerald-wealth',
    name: 'Emerald Wealth & Obsidian (Finance & Crypto)',
    category: 'Finance & Luxury',
    bgGradient: ['#032917', '#010d07'],
    primaryAccent: '#059669',
    highlightColor: '#10e778',
    textColor: '#ffffff',
    textMuted: '#a7f3d0',
    badgeBg: '#10e778',
    badgeText: '#000000',
    cardBg: 'rgba(3, 41, 23, 0.9)',
    cardBorder: 'rgba(16, 231, 120, 0.45)',
    glowColor: '#10e778',
  },
  {
    id: 'luxury-gold',
    name: '24K Champagne Gold & Jet Black (Luxury)',
    category: 'Finance & Luxury',
    bgGradient: ['#1c160a', '#080602'],
    primaryAccent: '#d97706',
    highlightColor: '#ffdf00',
    textColor: '#ffffff',
    textMuted: '#fde68a',
    badgeBg: '#ffdf00',
    badgeText: '#000000',
    cardBg: 'rgba(28, 22, 10, 0.9)',
    cardBorder: 'rgba(255, 223, 0, 0.45)',
    glowColor: '#ffdf00',
  },
  {
    id: 'crypto-diamond',
    name: 'Diamond Ice Blue & Titanium (Tech & Web3)',
    category: 'Finance & Luxury',
    bgGradient: ['#081d33', '#020912'],
    primaryAccent: '#38bdf8',
    highlightColor: '#67e8f9',
    textColor: '#ffffff',
    textMuted: '#bae6fd',
    badgeBg: '#38bdf8',
    badgeText: '#000000',
    cardBg: 'rgba(8, 29, 51, 0.9)',
    cardBorder: 'rgba(56, 189, 248, 0.45)',
    glowColor: '#38bdf8',
  },

  // 4. Urgency, News & Drama
  {
    id: 'crimson-alert',
    name: 'Crimson Alert & Pitch Black (Breaking News)',
    category: 'Urgency & News',
    bgGradient: ['#2e0404', '#0a0000'],
    primaryAccent: '#dc2626',
    highlightColor: '#ff1e1e',
    textColor: '#ffffff',
    textMuted: '#fca5a5',
    badgeBg: '#ff1e1e',
    badgeText: '#ffffff',
    cardBg: 'rgba(46, 4, 4, 0.92)',
    cardBorder: 'rgba(255, 30, 30, 0.55)',
    glowColor: '#ff1e1e',
  },
  {
    id: 'toxic-hazard',
    name: 'Toxic Biohazard Yellow & Carbon (Urgent Alert)',
    category: 'Urgency & News',
    bgGradient: ['#1c1a04', '#060601'],
    primaryAccent: '#ca8a04',
    highlightColor: '#ffea00',
    textColor: '#ffffff',
    textMuted: '#fef08a',
    badgeBg: '#ffea00',
    badgeText: '#000000',
    cardBg: 'rgba(28, 26, 4, 0.9)',
    cardBorder: 'rgba(255, 234, 0, 0.5)',
    glowColor: '#ffea00',
  },
  {
    id: 'true-crime',
    name: 'True Crime Blood Moon & Deep Shadow',
    category: 'Urgency & News',
    bgGradient: ['#1e0810', '#060103'],
    primaryAccent: '#991b1b',
    highlightColor: '#ff3366',
    textColor: '#ffffff',
    textMuted: '#fecdd3',
    badgeBg: '#ff3366',
    badgeText: '#ffffff',
    cardBg: 'rgba(30, 8, 16, 0.92)',
    cardBorder: 'rgba(255, 51, 102, 0.45)',
    glowColor: '#ff3366',
  },

  // 5. Minimalist, Modern & Contrast Clean
  {
    id: 'monochrome-bold',
    name: 'Monochrome Pitch Black & White (Minimal Punch)',
    category: 'Minimal & Clean',
    bgGradient: ['#141416', '#000000'],
    primaryAccent: '#e4e4e7',
    highlightColor: '#ffffff',
    textColor: '#ffffff',
    textMuted: '#a1a1aa',
    badgeBg: '#ffffff',
    badgeText: '#000000',
    cardBg: 'rgba(24, 24, 27, 0.9)',
    cardBorder: 'rgba(255, 255, 255, 0.35)',
    glowColor: '#ffffff',
  },
  {
    id: 'studio-minimal',
    name: 'Modern Slate & Electric Coral (Clean Studio)',
    category: 'Minimal & Clean',
    bgGradient: ['#0f172a', '#020617'],
    primaryAccent: '#38bdf8',
    highlightColor: '#fb7185',
    textColor: '#ffffff',
    textMuted: '#94a3b8',
    badgeBg: '#fb7185',
    badgeText: '#ffffff',
    cardBg: 'rgba(15, 23, 42, 0.9)',
    cardBorder: 'rgba(251, 113, 133, 0.4)',
    glowColor: '#fb7185',
  },
  {
    id: 'sunset-orange',
    name: 'Sunset Magma & Midnight Violet (Entertainment)',
    category: 'High CTR',
    bgGradient: ['#2d074d', '#0c0116'],
    primaryAccent: '#f97316',
    highlightColor: '#ff7a00',
    textColor: '#ffffff',
    textMuted: '#fed7aa',
    badgeBg: '#ff7a00',
    badgeText: '#000000',
    cardBg: 'rgba(45, 7, 77, 0.9)',
    cardBorder: 'rgba(255, 122, 0, 0.45)',
    glowColor: '#ff7a00',
  },
  {
    id: 'deep-ocean',
    name: 'Deep Abyssal Aqua & Sapphire (Documentary)',
    category: 'Minimal & Clean',
    bgGradient: ['#042038', '#010a13'],
    primaryAccent: '#0284c7',
    highlightColor: '#00e5ff',
    textColor: '#ffffff',
    textMuted: '#bae6fd',
    badgeBg: '#00e5ff',
    badgeText: '#000000',
    cardBg: 'rgba(4, 32, 56, 0.9)',
    cardBorder: 'rgba(0, 229, 255, 0.45)',
    glowColor: '#00e5ff',
  },
];

export interface OverlayPreset {
  id: string;
  name: string;
  category: string;
  description: string;
  icon: string;
}

export const OVERLAY_PRESETS: OverlayPreset[] = [
  {
    id: 'vignette',
    name: 'Dark Vignette',
    category: 'Cinematic',
    description: 'Smooth outer edge shadow for focal contrast',
    icon: '◉',
  },
  {
    id: 'radial-glow',
    name: 'Spotlight Neon Aura',
    category: 'Vibrant',
    description: 'Intense center radiant glow with theme accent',
    icon: '☼',
  },
  {
    id: 'speed-lines',
    name: 'Action Speed Lines',
    category: 'High Energy',
    description: 'Anime / Manga urgency lines pointing inward',
    icon: '⚡',
  },
  {
    id: 'sunburst-rays',
    name: 'Radiant Sunburst Rays',
    category: 'Viral Hook',
    description: 'MrBeast style dynamic radiant comic rays',
    icon: '☀',
  },
  {
    id: 'cyber-grid',
    name: 'Cyber Tech Grid',
    category: 'Tech & Gaming',
    description: 'Futuristic perspective neon grid mesh',
    icon: '⊞',
  },
  {
    id: 'particles-sparks',
    name: 'Glowing Fire Sparks',
    category: 'Vibrant',
    description: 'Floating energy sparks and glowing embers',
    icon: '✦',
  },
  {
    id: 'halftone-dots',
    name: 'Comic Halftone Dots',
    category: 'Pop Art',
    description: 'Retro comic book pop-art dot matrix',
    icon: '⁖',
  },
  {
    id: 'warning-tape',
    name: 'Caution Crime Tape',
    category: 'Urgency',
    description: 'Diagonal black & yellow warning stripes',
    icon: '⚠',
  },
  {
    id: 'glitch-scanlines',
    name: 'Glitch CRT Scanlines',
    category: 'Tech & Gaming',
    description: 'Cyberpunk CRT horizontal monitor scanlines',
    icon: '☰',
  },
  {
    id: 'diagonal-slits',
    name: 'Diagonal Energy Slashes',
    category: 'High Energy',
    description: 'Sharp diagonal speed slashes and light cuts',
    icon: '▰',
  },
  {
    id: 'dark-fade-bottom',
    name: 'Bottom Subtitle Fade',
    category: 'Cinematic',
    description: 'Smooth black gradient ramp on lower canvas',
    icon: '⯆',
  },
  {
    id: 'none',
    name: 'Clean Gradient (No FX)',
    category: 'Minimal',
    description: 'Pure high-contrast background gradient',
    icon: '○',
  },
];

export const FONTS_LIST: FontPreset[] = [
  // Viral & Ultra Bold
  {
    id: 'anton',
    name: 'Anton (MrBeast / Ultra Punch)',
    category: 'Viral & Bold',
    css: '"Anton", Impact, sans-serif',
    weight: '400',
    previewName: 'ANTON',
    description: 'Iconic ultra-heavy YouTube headline font. Maximum punch and mobile readability.',
  },
  {
    id: 'archivo',
    name: 'Archivo Black (Heavy Display)',
    category: 'Viral & Bold',
    css: '"Archivo Black", "Arial Black", sans-serif',
    weight: '400',
    previewName: 'ARCHIVO',
    description: 'Massive solid geometric black weight for breaking announcements and shock hooks.',
  },
  {
    id: 'blackhan',
    name: 'Black Han Sans (Square Block)',
    category: 'Viral & Bold',
    css: '"Black Han Sans", sans-serif',
    weight: '400',
    previewName: 'BLACK HAN',
    description: 'Ultra-dense square block letters for extreme visual density and commanding attention.',
  },
  {
    id: 'paytone',
    name: 'Paytone One (Bold Casual)',
    category: 'Viral & Bold',
    css: '"Paytone One", sans-serif',
    weight: '400',
    previewName: 'PAYTONE',
    description: 'Friendly yet high-impact casual headline display for lifestyle, finance, and stories.',
  },

  // Condensed & Tall
  {
    id: 'bebas',
    name: 'Bebas Neue (Tall Condensed)',
    category: 'Condensed & Tall',
    css: '"Bebas Neue", "Oswald", sans-serif',
    weight: '400',
    previewName: 'BEBAS NEUE',
    description: 'The golden standard tall condensed font. Fits long titles in large sizes without wrapping.',
  },
  {
    id: 'teko',
    name: 'Teko Bold (Ultra-Tall Athletic)',
    category: 'Condensed & Tall',
    css: '"Teko", sans-serif',
    weight: '700',
    previewName: 'TEKO BOLD',
    description: 'Extreme vertical height and athletic energy for sports, high-energy challenges, and fitness.',
  },
  {
    id: 'oswald',
    name: 'Oswald Bold (Condensed News)',
    category: 'Condensed & Tall',
    css: '"Oswald", Impact, sans-serif',
    weight: '700',
    previewName: 'OSWALD',
    description: 'Refined condensed grotesque font for documentaries, news analysis, and tech reviews.',
  },

  // Gaming, Esports & Action
  {
    id: 'kanit',
    name: 'Kanit 900 (Esports Action Slant)',
    category: 'Gaming & Action',
    css: '"Kanit", sans-serif',
    weight: '900',
    previewName: 'KANIT 900',
    description: 'Super-energetic Thai/Latin display font favored by esports channels and fast tutorials.',
  },
  {
    id: 'russo',
    name: 'Russo One (Cyber / Sci-Fi Matrix)',
    category: 'Gaming & Action',
    css: '"Russo One", sans-serif',
    weight: '400',
    previewName: 'RUSSO ONE',
    description: 'Futuristic constructivist geometry for AI, software, hardware, and space deep-dives.',
  },
  {
    id: 'righteous',
    name: 'Righteous (Retro Neon Synthwave)',
    category: 'Gaming & Action',
    css: '"Righteous", cursive, sans-serif',
    weight: '400',
    previewName: 'RIGHTEOUS',
    description: 'Electrified 80s arcade and futuristic synth aesthetic for gaming, tech, and entertainment.',
  },

  // Playful, 3D & Reaction
  {
    id: 'lilita',
    name: 'Lilita One (Viral 3D / Cartoon)',
    category: 'Playful & 3D',
    css: '"Lilita One", cursive, sans-serif',
    weight: '400',
    previewName: 'LILITA ONE',
    description: 'Chunky rounded letterforms perfect for 3D bevels, reaction videos, and family entertainment.',
  },
  {
    id: 'bungee',
    name: 'Bungee (Chunky Arcade / 3D Block)',
    category: 'Playful & 3D',
    css: '"Bungee", cursive, sans-serif',
    weight: '400',
    previewName: 'BUNGEE',
    description: 'Heavy vertical rhythm and arcade banner presence for Minecraft, Roblox, and gaming.',
  },
  {
    id: 'marker',
    name: 'Permanent Marker (Viral Hand-Drawn)',
    category: 'Playful & 3D',
    css: '"Permanent Marker", cursive, sans-serif',
    weight: '400',
    previewName: 'MARKER',
    description: 'Raw felt-pen marker handwriting for mystery reveals, "EXPOSED", and challenge vlogs.',
  },

  // Cinematic, Luxury & Creative
  {
    id: 'cinzel',
    name: 'Cinzel 900 (Cinematic Gold & Luxury)',
    category: 'Cinematic & Luxury',
    css: '"Cinzel", serif',
    weight: '900',
    previewName: 'CINZEL',
    description: 'Dramatic classical Roman proportions for high-ticket finance, luxury, history, and movie analysis.',
  },
  {
    id: 'syne',
    name: 'Syne 800 (Avant-Garde Creative)',
    category: 'Cinematic & Luxury',
    css: '"Syne", sans-serif',
    weight: '800',
    previewName: 'SYNE 800',
    description: 'High-fashion editorial display with wide character widths for design, architecture, and creative essays.',
  },

  // Modern Clean & Geometric
  {
    id: 'montserrat',
    name: 'Montserrat Black (Modern Heavy)',
    category: 'Modern & Clean',
    css: '"Montserrat", "Arial Black", sans-serif',
    weight: '900',
    previewName: 'MONTSERRAT',
    description: 'Crisp, contemporary geometric monster weight. Clean, authoritative, and corporate-ready.',
  },
  {
    id: 'poppins',
    name: 'Poppins 900 (Geometric Punch)',
    category: 'Modern & Clean',
    css: '"Poppins", sans-serif',
    weight: '900',
    previewName: 'POPPINS',
    description: 'Perfect rounded geometry favored by tech YouTubers, productivity gurus, and developers.',
  },
  {
    id: 'inter',
    name: 'Inter Tight Black (Crisp Tech)',
    category: 'Modern & Clean',
    css: '"Inter Tight", "Inter", sans-serif',
    weight: '900',
    previewName: 'INTER TIGHT',
    description: 'Ultra-tight optical kerning for modern UI/UX tutorials, coding roadmaps, and SaaS breakdowns.',
  },
];

